name: chameleon
description: "A cinematic, minimal music player built with Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hicons: ^1.0.0
  flutter_screenutil_plus: ^1.6.0
  google_fonts: ^8.2.1
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.0
  youtube_explode_dart: ^3.1.0
  just_audio: ^0.10.6
  audio_service: ^0.18.19
  shared_preferences: ^2.5.5
  salomon_bottom_bar: ^3.3.2
  liquid_glass_easy: ^3.5.0
  just_audio_background: ^0.0.1-beta.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.svg